-- Tenet-0 events table + per-subscriber offsets

CREATE TABLE IF NOT EXISTS events (
  id TEXT PRIMARY KEY,  -- UUIDv7 generated by client
  event_type TEXT NOT NULL,
  source_department_id TEXT NOT NULL REFERENCES departments(id) ON DELETE RESTRICT,
  payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  parent_event_id TEXT REFERENCES events(id) ON DELETE SET NULL,
  constitution_version_id BIGINT NOT NULL,  -- FK added in migration 003 after table exists
  published_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_events_published_at ON events(published_at DESC);
CREATE INDEX IF NOT EXISTS idx_events_type_published ON events(event_type, published_at DESC);
CREATE INDEX IF NOT EXISTS idx_events_source_published ON events(source_department_id, published_at DESC);
CREATE INDEX IF NOT EXISTS idx_events_parent ON events(parent_event_id) WHERE parent_event_id IS NOT NULL;

-- Subscription offsets
CREATE TABLE IF NOT EXISTS event_subscriptions (
  id BIGSERIAL PRIMARY KEY,
  department_id TEXT NOT NULL REFERENCES departments(id) ON DELETE CASCADE,
  subscription_key TEXT NOT NULL,
  pattern TEXT NOT NULL,
  last_consumed_event_id TEXT REFERENCES events(id) ON DELETE SET NULL,
  last_heartbeat_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (department_id, subscription_key)
);

CREATE INDEX IF NOT EXISTS idx_subs_dept ON event_subscriptions(department_id);

-- Archive table (rows moved here after 30 days, same shape)
CREATE TABLE IF NOT EXISTS events_archive (LIKE events INCLUDING ALL);

GRANT SELECT ON events TO tenet0_app;
GRANT SELECT ON events_archive TO tenet0_app;
GRANT SELECT, UPDATE ON event_subscriptions TO tenet0_app;
GRANT SELECT ON events TO tenet0_secops;
GRANT SELECT ON events_archive TO tenet0_secops;
GRANT SELECT ON event_subscriptions TO tenet0_secops;
